app1/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class ModelFilm(models.Model):
    class GenreChoices(models.TextChoices):
        Horreur = "H",
        Science_fiction = "SF",
        Comedie = "C",
        Drame = "D",
        Aventure = "A",
        Manga = "M",
        Thriller = "TH",
        Documentaire = "Doc"

    name = models.CharField(max_length=200)
    year = models.IntegerField(validators=[
        MinValueValidator(1950), MaxValueValidator(2022)])
    author = models.CharField(max_length=100)
    seen_or_not = models.BooleanField(default=False)
    genre = models.CharField(choices=GenreChoices.choices, max_length=25)
    official_page = models.CharField(max_length=150)

app1/forms.py
from django import forms
from app1.models import ModelFilm


class AddFilm(forms.ModelForm):
    class Meta:
        model = ModelFilm
        fields = '__all__'


class ContactUs(forms.Form):
    name = forms.CharField(max_length=150, label="Nom et prénom ", widget=forms.TextInput(attrs={'Placeholder': 'Votre nom et prénom'}))
    email = forms.EmailField(label="Votre email ", widget=forms.TextInput(attrs={'Placeholder': 'Votre email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'Placeholder': 'Votre message...'}), label="Votre message ")

app1/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect

from app1.forms import AddFilm, ContactUs
from app1.models import ModelFilm


def homepage(request):
    films = ModelFilm.objects.all()
    return render(request, 'app1/homepage.html',
                  {'films': films})


def movie_details(request, id):
    movie = ModelFilm.objects.get(id=id)
    return render(request, 'app1/movie_details.html',
                  {'movie': movie}) 


def add_movies(request):
    if request.method == "POST":
        form = AddFilm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movie_details', movie.id)
    else:
        form = AddFilm()

    return render(request, 'app1/add_film.html',
                  {'form': form})


def contact(request):
    if request.method == 'POST':
        form = ContactUs(request.POST)
        if form.is_valid():
            send_mail(
                subject=form.cleaned_data['name'],
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['monadresse@django.be']
            )
            return redirect('homepage')
    else:
        form = ContactUs()

    return render(request, 'app1/contactus.html',
                  {'form': form})

app1/templates/app1/add_film.html
{% extends 'app1/base.html' %}
{% load tailwind_filters %}
{% block content%}

<h1 class="mb-5 text-xl">Voulez-vous ajouter un film?</h1>

    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button>Envoyer</button>
        </form>
    </div>


{% endblock %}

app1/templates/app1/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Application django</title>
</head>
<body class="bg-gray-200 container sm m-auto">
    <header>
        <nav class=" h-24 flex justify-center align-center mt-5">
            <ul class="flex justify-around p-2.5 w-2/4 m-auto">
                <li><a href="{% url 'homepage' %}" class="px-5 py-2.5 bg-white hover:bg-blue-500 rounded-full hover:text-white">Home</a></li>
                <li><a href="{% url 'add_movies' %}" class="px-5 py-2.5 bg-white hover:bg-blue-500 rounded-full hover:text-white">Add a movie</a></li>
                <li><a href="{% url 'contact_form' %}" class="px-5 py-2.5 bg-white hover:bg-blue-500 rounded-full hover:text-white">Contact us</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <!--Contenu spécifique aux templates-->
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <!--Footer -->
    </footer>
    <script src="https://cdn.tailwindcss.com"></script>
</body>
</html>

app1/templates/app1/contactus.html
{% extends 'app1/base.html' %}
{% load tailwind_filters %}
{% block content%}

<h1 class="mb-5 text-xl">Voulez-vous nous contacter?</h1>

    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button >Envoyer</button>
        </form>
    </div>

{% endblock %}

app1/templates/app1/homepage.html
{% extends 'app1/base.html' %}
{% load tailwind_filters %}
{% block content%}

<h1 class="text-3xl mb-24 mt-24">Voici les films de votre liste :</h1>

<ul class="flex flex-col justify-center">
    {% for elem in films %}
    <li class="mb-5">

        <a href="{% url 'movie_details' elem.id %}" class="text-xl hover:text-blue-500">{{elem.name}}</a>
    </li>
    {%endfor%}
</ul>

{% endblock %}

app1/templates/app1/movie_details.html
{% extends 'app1/base.html' %}
{% block content%}

<h1 class="text-3xl mb-24 mt-24">Voici les détails du film : " {{movie.name}} " </h1>

<ul>
    <li class="list-disc list-none mb-5 text-xl">Année de production : {{ movie.year }}</li>
    <li class="list-disc list-none mb-5 text-xl">Responsable cinématographique : {{ movie.author }}</li>
    <li class="list-disc list-none mb-5 text-xl">Avez-vous vu ce film? {{ movie.seen_or_not|yesno }}</li>
    <li class="list-disc list-none mb-5 text-xl">Le genre de ce film : {{ movie.get_genre_display }}</li>
    <li class="list-disc list-none mb-5 text-xl">Page du film : <a href="{{ movie.official_page }}" target="_blank" class="hover:text-blue-500">{{ movie.name }}</a></li>
</ul>

<a href="{% url 'homepage' %}" class="hover:text-blue-500">Retour à la page des films</a>
{% endblock %}